version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:17-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 7484d6e16e063dc617bbb636d8b189e6e9760af2
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_DB_USER}
      POSTGRES_PASSWORD: ${PG_DB_PASS}
      PGDATA: "${PG_DB_DIR}/pgdata"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:${PG_DB_DIR}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot -d sendman_bot"]
<<<<<<< HEAD
=======
=======
>>>>>>> 7484d6e16e063dc617bbb636d8b189e6e9760af2
      POSTGRES_DB: "suggest_bot"
      POSTGRES_USER: "bot"
      POSTGRES_PASSWORD: "pgpwd4bot"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bot -d suggest_bot"]
<<<<<<< HEAD
=======
>>>>>>> b280105098c89b8eada8000806df4951558d0087
>>>>>>> 7484d6e16e063dc617bbb636d8b189e6e9760af2
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> 7484d6e16e063dc617bbb636d8b189e6e9760af2
    networks:
      default:
        ipv4_address: ${PROJECT_IP_MASK}.10

<<<<<<< HEAD
=======
=======
>>>>>>> b280105098c89b8eada8000806df4951558d0087
>>>>>>> 7484d6e16e063dc617bbb636d8b189e6e9760af2
